name: Lint and Test

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches:
      - dev
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.10
            3.11
            3.12
            3.13
      - run: |
          pip install uv
          make install-ci
          make test
