name: Test 🧪

on:
  pull_request:
  push:
    branches:
      - dev
      - master

jobs:
  test:
    name: Run tests 🧪
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y poppler-utils
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov=src --cov-report=xml --cov-report=html